-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 23, 2017 at 04:57 PM
-- Server version: 5.7.19
-- PHP Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `placements`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

DROP TABLE IF EXISTS `data`;
CREATE TABLE IF NOT EXISTS `data` (
  `compname` varchar(50) NOT NULL,
  `details` varchar(5000) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`compname`, `details`) VALUES
('BAY CURRENT(JAPAN)', 'Branches Open for: B.Tech- All Came around: October end Process: Resume Shortlist +2 Tests+2 Interviews CG cutoff (if any): No Type of Interview: HR+Tech Major areas concentrated in the test: Practice test links mentioned Major areas concentrated in the interview: Technical: Case Study & Guesstimates HR: PoRs, Resume review, ability to memorize fast Sample questions in the interview: HR: 1. A complex symbol was drawn to replicate 2. What was your second year internship about? 3. How many hours will you dedicate to learn Japanese? (Selected candidates expected to learn before internship starts) Tech: 1. Estimate the market size of badminton in India 2. If a company X has declining revenues, what might be the possible reasons? 13 Preparation to be done: 1. Case studies on YouTube 2. Heard on the street 3. Guesstimates on the internet 4. https://www.cebglobal.com/shldirect/en/practice-tests (link given by company)'),
('AXIS BANK', 'Branches Open: All B.Tech and Dual Degree Students Came around: 4 rd week of September Process: Resume Shortlist + Test + Interview CG cutoff (if any): No GD topic: No GD Type of Interview: Technical Skype Interview and HR Interview Major areas concentrated in the test - Problem solving on HackerEarth- 4 hours were given to analyze a Data Set. Eg. IMDB Database was shared with 20 or so columns. Although excel can be used, brownie points given to those using the R software Major areas concentrated in the interview: 1. Technical: Guess estimates, Puzzles 2. HR: Resume based Questions Sample questions in the interview: 1. Technical: Guess the number of people online on Facebook right now? HR: Can you tell me more about the project you did?'),
('AMERICAN EXPRESS', 'Branches Open for: B.Tech & Dual: All Came around: August Process: Resume Shortlist + Test + Interview CG cutoff (if any): CS/Elec-8, Others-8.5 Type of Interview: 2 Technical +1 HR Major areas concentrated in the test: 45 minutes test including aptitude as well as tech questions Major areas concentrated in the interview: Technical: Analytics questions, questions based on- Probability, Statistics, Hypothesis testing, Stochastic processes, Coding-Python, R HR: Primarily questions about resume Sample questions in the interview: Tech: Questions from MA2040 HR: 1. Talk about yourself. 2. Why analytics? 3. Why Amex? 4. About second year internship Preparation to be done: 1. Good resume with good CGPA Revise Probability & Statistics'),
('ADOBE', 'Branches Open for: B.Tech- Computer Science, Electrical Dual-Computer Science Came around: End of August Process: Resume Shortlist+ Online Test CG cutoff (if any): 8.5 (Also Direct offer to top 3 students of CS) Preparation to be done: 1. Suggestion: http://www.geeksforgeeks.org/ Students can use this site as a practice for test. 2. https://www.interviewbit.com/ also for practice'),
('AMAZON INDIA', 'Branches Open for: All Process: 1. Two programming tests 2. Two tech Interviews CG cutoff(if any): 7.5 Type of Interview: Technical Major areas concentrated in the test 2 programming questions and 18 MCQs (Hackerank) - in the first test, 1 coding question - in the second tests Major areas concentrated in the interview: Technical : Coding skills Sample questions in the interview: 3 questions each from tech in each round Preparation to be done: 1. Data Structures and Algorithms 2. Geeksforgeeks 3. competitive programming'),
('AB INBEV', 'Profile- Analytics/Consulting/Finance Branches Open for: B.Tech - All Braches; Dual Degree - Computer Science & Engineering Came around: 2nd week of November Process: Resume shortlist, GD was supposed to happen but couldn\'t because of time scarcity. Then Interview CG cutoff (if any): Mostly 8 Type of Interview: Technical + HR Major areas concentrated in the interview: Technical: Data analytics, mostly about data engineering HR: Very basic questions Sample questions in the interview: Technical: 1. Many questions related to data structures 2. Operations Research related one question-how many bottles should be kept in one carton to prevent from damage given a few constraints and a very big statement (candidate required to convert it into analytical question and give the outputs. ) HR: 1. What motivates you in life and why? 2. Biggest achievement in data analytics and why our company? Preparation to be done: Placement Material'),
('CAPITAL ONE', 'Branches Open for: B.Tech - All Branches Came around: 4th week of August Process: Written Test + Case Study + Personal Interview CG cutoff (if any): No GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical (2 rounds) + HR Major areas concentrated in the interview: 1. Technical: 1. They gave a case study and asked for efficient output (pseudo code description) 2. Problem solving abilities, Slight coding, Structured way of solving a case 2. HR: There was a discussion about the candidate’s career plans & The work he would be doing during the intern 14 Sample questions in the interview: Technical: 1. Regarding transport, they give 10 vehicles including their velocity, mileage and which route they have to travel and you have to develop an efficient output for less amount to spend 2. There are 3 people who have priority to do a work like low, medium, high priorities. They have 54 tasks, each task has a priority and time to get it done. Each person has 80 hours total of 240 hours. Each person has to complete all the tasks in 240 hours and if this doesn’t happen they have to tell how much extra time did it take 3. Various tasks along with priority and the number of hours 4 people take to finish a particular task and their priorities were given and you are supposed to calculate how many extra hours are needed. And write a pseudo code for the same. 4. Question similar to a ecommerce companies routing problem and a pseudo code for that had to be written. Preparation to be done: 1. Not company specific preparation, use hackerank to practice coding Have mock GDS and discuss about GDs with people. This will help solve the cases efficiently.'),
('CITICORP', 'Branches Open for: IT: B.Tech-All Analytics: B.Tech-Computer Science, Electrical & Mechanical Came around: 2nd week of September IT profile: Process: Resume Shortlist + Test + Interview CG cutoff (if any): No Type of Interview: Technical + HR Major areas concentrated in the test: Aptitude & Programming concentrated on. Prediction of output or writing code in language of your choice. Major areas concentrated in the interview: Technical: Coding skills (programming related) HR: Resume based Sample questions in the interview: HR : 1.Why do you want to work at CitiCorp? 2. Why are you interested in IT field and coding? 3.Why are you interested in the particular POR. 16 Preparation to be done: 1. Online Tests to improve programming skills 2. Algorithms 3. Programming languages - C, C++, Java (any 1 is sufficient) Technology Profile: Process: Resume shortlist+Test + Interview CG cutoff for test: No cg cutoff Major areas concentrated in the test: Three parts- logical reasoning, coding outputs and code writing Type of Interview: Technical+ HR Major areas concentrated in the interview: Tech: Probability & Algorithms, Programs from sorting, stack, writing pseudo code, Puzzles in both. HR interview: Resume based, interest in various topics, leadership quality Sample questions in the interview: 1. Explain different sorting algorithms. Which one do you consider best and why? 2. Explain the concept of stack & linked list? 3. Why are you interested in a particular POR? 4. Why Citicorp? Why this profile? Preparation to be done: 1. Programming course done earlier 2. Online programming tutorials 3. Heard on Street for puzzles '),
('EATON TECHNOLOGIES', 'Branches Open for: Dual Degree - Electrical, Mechanical and Engineering Design Came around: 2nd week of November Process: Resume shortlist + Personal Interview CG cutoff (if any): Yes. 2 from Mech, Elec Dual and ED were shortlisted based on CG. It was around 8.5 for Mechanical and Engineering Design and 8 for Electrical. GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical and HR (One round each) Major areas concentrated in the interview: 1. Technical: Topics interested, Resume based(especially internships & projects), specialization, Vehicle Dynamics & Fluid Mechanics 2. HR: General questions on ethics and personal life Sample questions in the interview: Technical: 1. Why Diesel Engines have higher compression ratio than SI engines 2. How do you increase the efficiency of a truck? What design principles do you follow? 3. What is the control concept involved in a gear box design? 4. What happens if you use diesel in petrol engine and vice versa? 18 HR: 1. Tell me about yourself and your past. 2. Tell me something that you DO NOT want to do in future. 3. What do you want to do after 5 years? 4. Tell some recent advancements in the core field and/or current affairs. 5. Why do you want this internship / company and what were your expectations from this interview? 6. Do you wish to continue studies after your degree? 7. What are your strengths & weaknesses? Preparation to be done: 1. Core coursework especially specialization 2. Preparation and research on companies Preparation material: 1. Fluid Mechanics by Fox. 2. Control Theory from Ogata K. 3. Thermodynamics by P.K. Nag'),
('EDGEVERVE SYSTEMS LTD', 'Branches Open for: B.Tech - CS Came around: 3rd week of September Process: Online coding contest on Hackerank + Personal Interview CG cutoff (if any): They wanted students who have scored more than 70% in CSE GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical + HR (One round only) Major areas concentrated in the test - No Test Major areas concentrated in the interview: 1. Technical: Data structures, Algorithms and Operating Systems 2. HR: They asked him about the projects and internships he had done, Career plans and his subject interests. Sample questions in the interview: Technical: 1. How the cache is organized in a computer in first level and second level cache 20 HR: i. What field of Computer science he was interested in? ii. Tell about the startup that you interned in in the last summer. Preparation to be done: i. Prepared many coding questions from online websites preferably in object oriented language like Python and C++. Questions on dynamic programming, backtracking and recursion on Hackerank are very good for practice'),
('XML SERVICES INDIA PVT LTD', 'Branches Open for: ALL Came around: 2 nd week of September Process: Resume shortlist (80 deleted) + Telephonic Interview (40 selected) + Test (10 selected) + HR Interview (5 selected) CG cutoff(if any): 8 Major areas concentrated in the test - It involved 3 data interpretation questions, one famous. One probability question and one case study question Type of Interview: Aptitude for the Telephonic interview and HR one on one Major areas concentrated in the interview: Technical : Guesstimate and Puzzles HR: Journey in IIT. Sample questions in the interview: Telephonic interview :- ? Estimate the revenue of Murugan Idli food chain in Chennai ? If there are 9 coins, 8 of which are of the same weight and one is heavier than the rest, how many iterations with a Weight balance will it take to find the faulty one? 22 HR :- Tell me about our journey at IIT. Why EXL tell us about your interest in this field. Preparation to be done: 1. Herd on the Street, Guesstimate from Analytics Vidhya and Basic 2. Puzzles from standard books'),
('GENERAL ELECTRIC(GE)', 'Branches Open for: Dual Degree - AE, CS, EE, ME, MM Process: Resume Shortlist + Test + Interview CG cutoff(if any): 8.5 Type of Interview: Technical + HR Major areas concentrated in the test - Tech related Major areas concentrated in the interview: Technical : Gas dynamics Sample questions in the interview: HR : General questions like tell me about yourself? Why do you want to join our company? Talk about your internship. Tech :Explain the physics of a condi nozzle Preparation to be done: Coursework '),
('GLOBOCON TECHNOLOGY', 'Branches Open for: All Process: Resume Shortlist + Telephonic Interview CG cutoff(if any): No Type of Interview: Technical + HR Major areas concentrated in the interview: Technical : Projects related to analytics ( R language) HR: Basic (Asked him about preferred location) Sample questions in the interview: HR : basic questions Preparation to be done: 1. R language (Google) 2. Online Finance courses'),
('GOLDMAN SACHS', 'Open for: All branches Came Around: Day 1 company Process: There was a test based on which the shortlist was done. The test itself had 3 sections -Computer Science, Quant and Machine Learning. (Do remember that the pattern wasn’t the same last year.). Time wasn’t an issue. The questions were based on CS and ML (CS section was not just about knowing C/C++) .The shortlist is NOT based on your total marks. The topics each apply to a different profile. So, it’s safe to assume that you’d get shortlisted, you have to do really well in at least one topic. Major areas concentrated in the interview: Technical - ~10 rounds in all. The questions depended on what the profile was though all the interviewers tested aptitude. So, a couple of the interviews involved them tweaking something to make a code more efficient .There was also this one round where they taught concepts and then asked the candidate to solve a problem based on it. The topics were mainly 1.Probability 2. Permutations and Combinations 3. Linear Algebra 4. Coding - Arrays, Linked lists, sorting. They concentrate on using minimum space complexity. 5. Algebra. 26 Sample questions in the interview: 1. Questions on finding Expectation values of infinite possibilities scenario: There’s a pentagon. AB - Diagonal. A bug at A should go to B. What is the expectation value of this, if it has equal probability of going right or left? 2. There’s a plane. Dots are arranged so that no dot has another dot of the same colour in it’s line of dot. How many colors do you need? 3. There are n buckets. Each bucket as a capacity (different) of Ci. There’s a tank with capacity, L. Objective is to empty the tank L into the buckets such that they’re shared equally. For Eg. There are 3 buckets - A(2L), B(4L), C(5L). Tank’s capacity is 9L. 9/3=3&gt;capacity of A. So, Put 2L in A. (9-2)/2=3.5. Put 3.5L each in B and C. Write code for this. 4. There are 25 horses. 5 horses race at a time. Find the minimum no. of steps for finding 5 fastest horses? 5. Dynamic Programming Question: You can go only 1 or 2 steps at a time. Find the no. of ways of reaching the nth point in the number line starting from n=0? Preparation: 1. Geeksforgeeks (Online Website) - Previous Goldman Sachs Interviews 2. Introduction to Algorithms by Thomas H. Cormen - For coding, data structures and algorithms 3. Probability - +2 knowledge is sufficient 4. Do some puzzles online'),
('HINDUSTAN UNILEVER', 'Branches Open for: B.Tech & Dual- Mechanical & Chemical Came around: August Process: Resume Shortlist + GD + 2 rounds of Interview CG cutoff (if any): Around 7 GD topic- Case study Suppose you are a manager of a factory. To meet the demands of the factory you need to start a machine which has a high chances of breakdown. On the other hand if the machine is under maintenance, there will be a shutdown and it will incur high costs. Also production will be decreased. What is your take on this? How will you keep the production going with the machine? Type of Interview: Technical + HR Major areas concentrated in the interview Technical: Core Intern and Favorite subject (Fluid mechanics for example) HR: Basic-Tell us about yourself - Resume - Why do you want to join? Sample questions in the interview: HR: Tell us about yourself? Why do you want to join? Preparation to be done: Coursework, theory of thermodynamics and fluid mechanics'),
('INFOSYS', 'Branches Open for: 1.Computer Science Engineering 2.Electrical Engineering Process: Initial resume shortlist followed by a telephonic interview CG cut off: Not mentioned Type of interview: Technical Telephonic Interview Subjects concentrated in tech interview: Computer Organisation Sample questions from each type of interview: Tech: 1. Array declaration in python 2. Basic questions on Github (because mentioned in resume) 3. Number of spanning graphs in the given graph (graph theory mentioned) Preparation: Course material should do'),
('ITC', 'Process: ITC Application Shortlist (Resume + Some HR questions), Group Discussion, 2 rounds of interviews CG cutoff(if any): No Topic of the GD: A case study to determine the most culpable entity in the death of a person Expectations of the moderator: Ability to guide discussions, lead, generate solutions, critical points and arrive at a conclusion in a systematic manner. Type of Interview: Tech+HR Major areas concentrated in the interview: Technical : Core Subjects - Machines,EMF,DSP etc HR: General questions - Refer Google Sample questions in the interview: Telephonic interview :- 1. How does the speed of an induction motor vary with voltage, number of poles, frequency etc? 2. How would you construct a supply chain for biscuits? What are the inputs, outputs, processes involved, and factors which could cause fluctuations and instabilities in the system? 31 HR: 1. Why do want to work at ITC although you are an electrical engineer? 2. Explain your summer intern project and its impact. Preparation to be done: 64 HR Questions (Available on DC), Coursework'),
('JSW', 'Branches Open for: B.Tech - All branches. Came around: 1 st week of November. Process: Resume Shortlist + Aptitude + Personal Interview CG cutoff (if any): No Type of Interview: HR Major areas concentrated in the interview: One should have thorough knowledge about company and its business. Along with this, you should be thorough with your Resume and the application form which they ask you to fill as part of their recruitment process. Sample questions in the interview: HR Questions: 1.Tell me about one of the PORs which you have done in your institute life. 2.And standard questions like tell me about yourself, why JSW etc. Preparation to be done: 1.Go through company’s website and some of their recent achievements'),
('J P MORGAN', 'Branches Open for: 1. B.Tech - All Branches 2. Dual Degree - All Branches Came around: 1 st week of November CG cut-off: Not explicitly mentioned (trend was around 8) Process: Resume shortlist + Personal Interview Type of Interview: Technical (2 rounds) Major areas concentrated in the interview: 1. Technical: Probability questions & Coding 2. HR: Not much HR questions Sample questions in the interview: Technical: Question on hash maps, Binary Search Preparation to be done: 1. Algorithms, Data science and probability. 2. Practice puzzles from Heard on the Street'),
('MICROSOFT', 'Open for: B.Tech - CS, EE Dual Degree - CS, EE Process: 1.Online coding test: 7 were selected directly for interview and 15 for group fly round. 2.Group Fly Round: Students were divided into groups and given a mentor each. Then students had to solve problems given to the individually. They were algorithm based questions and students had to write pseudo code for them. 8 were selected for interview. 3.Total 15 students were selected for interview. Major areas concentrated in the interview: 1.Data Structures and Algorithms 2.Basic Computer Hardware 3.Computer Organisation Sample questions in the interview: 1.Given a sequence of Red, Green and Blue balls, sort them in the order Red first, then Green and then Blue in O(n) time. Remember that you cannot change the colors of the balls, they only need to swapped. 2.Given a number(may have arbitrarily large number of digits), find the smallest palindrome greater than the given number. 3.Given a 2-D array, write an algorithm which prints the elements present in all the rows. Do it in optimal time and space. 4.Given an image, if the image is represented as a 2D array of pixels. Write an algorithm to rotate the image by 45 O , 90 O and to flip it. 35 Preparation to be done: 1. www.interviewbit.com 2. Basic books on data structuring. 3. Introduction to algorithms by CLRS. 4. Competitive programming on sites like Hackerrank , Codechef etc. 5. Concepts of Data Structures from Cormen'),
('MONDELEZ INTERNATIONAL', 'Branches Open for: Dual Degree: Chemical & Mechanical Came around: 2nd week of October Process: Resume Shortlist + GD + Interview CG cutoff (if any): No GD topic: How food industry can leverage the growth of e-commerce? What were the expectations from the moderator during GD? It was mostly about making a reasonable point and involving yourself in the discussion. Moderator also checked if the person who put forward an argument was able to defend it or not, if need be. Type of Interview: Technical + HR Major areas concentrated in the interview: Technical: Tech questions related to projects done HR: Why Projects done, why POR taken up? Sample questions in the interview: HR: 1.Story of your life. 2. How are you as a person? Preparation to be done: 1. Be thorough with topics mentioned in resume 2. 64 HR questions '),
('NOMURA', 'Branches Open for: B.Tech - All Came around: Day 1 Company Process: Resume Shortlist + GD + Personal Interview CG cutoff (if any): Not mentioned explicitly GD topic (Mention this only if there was a GD else ignore): 1. If India had to increase its medal tally in the Olympics, should more emphasis on investments come from government or corporates? Expectations from the Moderator (during GD): No right answer was expected. The moderator was looking at the relevance of points put forth. How one works in a work environment, as a group. Type of Interview: There were two rounds of tech interview and a final HR interview. Major areas concentrated in the interview: Technical: 1. The questions asked in the tech interview were very financial. 2. Questions on the candidate’s 2nd year internship were asked. Puzzles were also asked. 3. Since the candidate was an enthusiast in cricket , he was asked how he would get Cheteshwara Pujara out (basically focusing on strategy formation and approach to questions). 38 Nomura HR: 1. Asked about background about second year internship in terms of working aptitude. Questions on yourself. Sample questions in the interview: Technical: 1. Differentiate between ‘forwards’ and ‘futures’ using task flows; 2. Basic Profit and Loss question HR: 1. Differences between FDI and FTI. 2. How would you reduce inflation as Raghuram Rajan or Narendra Modi. Preparation to be done: 1. For the puzzles refer to ‘Herd on the Street’(Wall Street puzzles), Quora puzzles 2. Watched a documentary on Financial history of the world . 3. Online courses called: Financial Engineering Part-1 and Introduction to Finance Theory.[All of these freely available online]'),
('NOMURA2', 'Branches Open for: B.Tech - All Came around: Day 1 Company Process: Resume Shortlist + GD + Personal Interview CG cutoff (if any): Not mentioned explicitly GD topic (Mention this only if there was a GD else ignore): 1. “Should RBI have changed the benchmark rate during the recent meeting” 2. Discuss conditions and figure out whether or not it would be conducive for Nomura to set up fresh operations at London in the wake of Brexit. Expectations from the Moderator (during GD): No right answer was expected. It was more of a test on the candidates’ knowledge regarding RBI, interest rates, etc. So this round was a filter on the basis of background knowledge in finance and economics. Type of Interview: There were 5 rounds of tech interview. The first 2 rounds and the last 3 rounds were conducted by separate panels. No formal HR interview was conducted. Major areas concentrated in the interview: Technical: 1. The questions asked by the first panel mainly tested basic knowledge in finance and economics. 2. The second panel concentrated on a lot of case studies. 3. Also general puzzle-type questions were asked. 4. It was like a financial quiz where a lot of questions were asked with short answers. 40 Nomura 5. Also guestimate questions were asked. Sample questions in the interview: Technical: Given a 16 squares a side Chess board how you would place 4 queens such that none of them are in firing line. Preparation to be done: No specific preparation done. Generally going through puzzles, brushing up general awareness on financial scenario, etc.\r\n'),
('P & G', 'Branches Open for: B.Tech - AE, CH, EE, ME, MM Dual Degree - AE, CH, EE, ME, MM Process: 1.Psychometric test 2.Reasoning test 3.Interview - 2 Rounds. Type of Interview: There were two rounds of interviews and both of them were HR interviews. Areas concentrated in HR interview: 1.They gave situations and asked how they would react to those situations. 2.They asked for examples of situations when she had shown leadership skills, solved a problem or taken any initiative. Sample questions in the interview: Questions were regarding how you would react to the given situations - 1.When you are working on multiple projects and one or two of them are showing any progress? 2.When your supervisor asks you to complete some tasks in 2 days instead of the two weeks he had given earlier? 3.When you want to change something, how will you convince the older staff? 42 Other questions asked in the interview: 1. You have 4 projects. Their deadlines are as follows - 1. Tomorrow 2. Next week 3. One Month later 4. 6 Months later How will you prioritize your work? 1. You are working on a project and putting a lot of effort but suddenly your boss says that you have been transferred to another project before your original project reached completion. How will you respond? 2. Narrate an incident where you joined a team and did something different from the rest and created an effective impact. 3. Narrate an incident from the past where you had to make a tough choice between two things and how did you make this decision. 4. Narrate an incident where you displayed leadership and lead a team despite inherent difficulties. Preparation to be done 1) Thermodynamics - P.K. Nag 2) Fluid Mechanics - Gupta and Gupta 3) Mass Transfer - Class notes 4) 64 HR questions 5) Practiced answering HR questions with friends'),
('QUALCOMM', 'Branches Open for: B.Tech & Dual- Computer Science & Electrical Came around: 2nd week of September Software profile: Process: Test + Personal Interview CG cutoff (if any): No Type of Interview: 2 Technical + 1 HR Major areas concentrated in the test: 3 major sections-aptitude, basic programming & Hardware/Software/Communication (Questions were tricky and speed was key) Major areas concentrated in the interview: Technical (Software): Coding skills, Lots of questions on pointers & their types, basics of OS (mentioned as a specialization in the profile) Technical (Communication): Digital Signal Processing and Networks & Systems. Questions from Digital Systems and Basic RC networks with diodes were asked HR: General Interests, Background Sample questions in the interview: Tech: 1. Explain difference between Call by reference & call by value. (Software) 2. There’s a grid of parallel lines, m horizontal & n vertical. Find the number of parallelograms 3. Nyquist’s Sampling Theorem 44 HR : 1.Where do you belong to? 2. An event which changed your life? 3. What does your dad do? Preparation to be done: 1. C Programming & Syntax 2. Course Material'),
('SALESFORCE', 'Branches Open for: 1. B.Tech - Computer Science & Engineering 2. Dual Degree - Computer Science & Engineering Came around: 3rd week of September Process: Test + Personal Interview CG cutoff (if any): No CG cutoff GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical Major areas concentrated in the test - Coding round and the written test covered all aspects of CSE Major areas concentrated in the interview: Technical: Data Structures and Algorithms Preparation to be done: 1. A website called InterviewBit'),
('SAMSUNG', 'Branches open for - B.Tech - CS ; Dual Degree - CS Came around - 1 st Week of October Process: 1. Résumé shortlist 2. Test 3. Group Discussion Profile Offered: Research and Development Group discussion: Digital India: Solving society’s problems as an engineer. The group discussion was more like a Just a Minute session, where each candidate was asked to talk about the given topic. The topic was common to all and each candidate was asked to express his ideas and to solve the society’s problems. Moderator’s expectations: He (student) thought that the moderator wanted him to use his algorithms and logic to solve the society’s problems. He mentioned that he had to use his technical knowledge and skills to improve the standard of living. For example: Develop low cost smart devices which are easy to use. Material: 1.geeksforgeeks.com for some algorithms. 2.Essential Algorithms by Rod Stephens. 3.Quant and Machine Learning'),
('SCHLUMBERGER', 'Branches Open: All B.Tech and Dual Degree Students Came around: 4 rd week of October Process: Resume Shortlist + Skype Interview CG cutoff (if any): No GD topic: No GD Type of Interview: HR Major areas concentrated in the interview: HR: 1. Be thoroughly prepared with your resume with real life instances supporting each point. 2. English proficiency, PORs, future plans, how much you know about the company. 3. Thorough details about the company, your resume 48 Sample questions in the interview: 1. HR: 1. Tell me about yourself. Which of your PoRs did you think were most challenging and why? 2. Tell me about a challenging task you have undertaken recently. 3. Why do you think you are suitable to work in Schlumberger? 4. What do you know about the company and it\'s work? Preparation to be done: 2. I did solve a puzzle book, How to move Mount Fuji and Herd on the Street, shared by the internship team which helped me a lot in general throughout the process and not specifically Schlumberger. 3. 64 HR questions, Research about the company'),
('SYSTEMANTICS INDIA PVT LTD', 'Branches open for: B.Tech - Mechanical Engineering Came around: 1 st week of October Process: Resume Shortlist + Interview CG Cutoff (if any): 8.5 approx. Type of Interview: Technical + HR simultaneously Major areas concentrated in the interview: Technical : Kinematics and Dynamics of machinery, projects from the Resume. Since it is core mech company need to be sound with your courses. HR: interests , personal achievements. Sample questions in the interview: Tech: General questions about force balance, torque balance of a multi body system (what my peers told me). HR: 1. What are your interests and accomplishments'),
('TATA STEEL', 'Branches Open for: B.Tech: Mechanical, Metallurgical & Materials Came around: 2nd week of October Process: Test + GD + Interview CG cutoff (if any): No Type of Interview: Technical + HR Major areas concentrated in the test: English, aptitude, logical reasoning Major areas concentrated in the interview Technical: Topic of choice from the core courses HR: Resume based Sample questions in the interview: Tech: Iron Carbon Diagram, Stress Strain Curves, Alloys Preparation to be done: 1. All previous course material'),
('TEXAS INSTRUMENTS', 'Branches Open for: 1. B.Tech - EE, EP 2. Dual Degree - EE Came around: 4 th week of August Process: Test + Personal Interview CG cutoff (if any): No CG cutoff GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical + HR Major areas concentrated in the test - Data interpretation sets, One Probability question and a Marketing Case Study. Major areas concentrated in the interview: Technical: Department based questions HR: Personal questions, Interest in core Sample questions in the interview: Technical: 1. How does the Fourier Transform work? 52 53 HR: 1. Why are you interested in Core? 2. Would you switch to Non-Core in the future? Preparation to be done: Course material should suffice'),
('TITAN', 'Branches Open: B.Tech - CS, EE, ME, EP, CH, MM Dual Degree - CS, EE, ME, CH, CE, MM, PH Came around: 1 st week of April Process: Resume Shortlist + Interview CG cutoff (if any): No GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: Technical + HR Interview (only 1 round) Major areas concentrated in the test - No test Major areas concentrated in the interview: 1. Technical: 1. It was mechanical and manufacturing and not much was there 2. Purely based on the project 2. HR: they just checked communication and general skills 54 Sample questions in the interview: Technical: 1. Tell me about your projects in your last internship and what you learnt from it? 2. You are a mech engineer, why did you choose biomed engineering as your minor? 3. If you have a spectacle and if you have to make a device to hold that spectacle for testing then what design would you think of. Preparation to be done - 1. Read your class notes 2. See company\'s website. Learn about the leading product of their company and their rivals 3. 64 hr questions also'),
('VISA', 'Branches Open for: B.Tech and Dual Degree - Computer Science and Electrical Engineering Came around: 2nd week of October Process: Test + Interview CG cutoff (if any): No GD topic (Mention this only if there was a GD else ignore): No GD Type of Interview: HR Major areas concentrated in the test: Coding Test (Basic Coding) Major areas concentrated in the interview: HR: Work done in college (any kind, not only tech) Sample questions in the interview: HR: 1. How has the Institute treated you and what have you learnt in the past two years? 2. How do you think you would be an apt person for the role we\'re offering? Preparation to be done: Hackerrank Website and Practiced coding'),
('VMWARE', 'Branches Open for: 1.Computer Science Engineering 2.Electrical Engineering (B.Tech and Dual Degree) Process: Interview Type of Interview: 2 Technical Skype rounds + 1 Telephonic HR Major areas concentrated in the interview: Technical: Data Structures, OS, Networking HR: Strengths, Weaknesses &amp; Social Interaction Sample questions in the interview: HR: 1.Talk about yourself 2.Two good things which your friends would tell about you Tech: 1.Print Mirror Image of given Binary Tree 2.Delete a node from a linked list given only that node pointer(no head node pointer given) Preparation to be done: 1.CLRS Data Structures and Algorithms 2.Operating system concepts by Galvin and Silberschatz'),
('WIPRO', 'Branches Open for: BTech- Mechanical Process: Resume Shortlist + Interview CG cutoff(if any): 8.5 Type of Interview: Technical based on CV Major areas concentrated in the interview: Technical: 20 minutes mixed interview focused on the Projects done HR: CV based Sample questions in the interview: HR: 1. Talk about previous internship 2. Explain your style of working Preparation to be done: Revise Coursework'),
('WIPRO2', 'Branches Open for: BTech- Mechanical, Chemical Process: Resume Shortlist + Interview CG cutoff(if any): 8.5 Type of Interview: Technical based on CV Major areas concentrated in the interview: Technical: Mostly concentrated on 2nd year internship HR: CV based Sample questions in the interview: HR: 1. Talk about previous internship and what life lesson you learnt from it 2. Explain your style of working and prove how you are planned and organised Preparation to be done: 1. Revise core Coursework and resume thoroughly 2. 64 HR questions'),
('WRIG NANOSYSTEMS', 'Branches Open for: 1. B.Tech - All Branches 2. Dual Degree - All Branches Came around: 1 st week of October Process: Resume shortlist + Personal Interview Type of Interview: Technical (3 rounds) Major areas concentrated in the interview: 1. Technical: Resume based, puzzles and Guess estimate 2. HR: Not much HR questions Sample questions in the interview: Technical: Guess the total number of satellites and some puzzles. Preparation to be done: 1. Thorough understanding of the company 2. Practice puzzles from techinterview.com ');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
